package com.boostlab.app.model

data class BoostState(
    val selectedApp: BoostApp? = null,
    val showAdvancedSettings: Boolean = false,

    val isGameLaunching: Boolean = false,
    val gameLaunchError: String? = null,
    val gameBoostMessage: String = "Готов к запуску",
    val availableMemoryMb: Long? = null,
    val totalMemoryMb: Long? = null,
    val availableMemoryPercent: Int? = null,
    val deviceLowMemory: Boolean? = null,
    val lowRamDevice: Boolean? = null,
    val powerSaveMode: Boolean? = null,
    val thermalStatus: Int? = null,
    val networkValidated: Boolean? = null,
    val networkTransport: String? = null,
    val gameLaunchMode: GameLaunchMode = GameLaunchMode.SMART,
    val pinnedPackages: Set<String> = emptySet(),
    val remoteCatalogGames: List<CatalogGame> = emptyList(),
    val autoLaunchAfterNetworkBoost: Boolean = false,
    val confirmStop: Boolean = true,
    val debugLogging: Boolean = false,
    val showPing: Boolean = true,
    val autoSelectBestNode: Boolean = true,
    val preferredRegion: String = "AUTO",
    val boostMode: String = "SMART",
    val customDnsEnabled: Boolean = false,
    val customDnsServers: List<String> = emptyList(),
    val diagnosticLogEntries: List<String> = emptyList(),
    val appEvents: List<String> = emptyList(),
    val localUserId: String = "",
    val squadCode: String? = null,
    val friends: List<String> = emptyList(),
    val squadMessages: List<SquadChatMessage> = emptyList(),
    val squadOnlineUsers: List<String> = emptyList(),
    val squadSyncError: String? = null,
    val directPeerId: String? = null,
    val directMessages: List<SquadChatMessage> = emptyList(),
    val directSyncError: String? = null,
    val voiceCallState: String = "IDLE",
    val voicePeerId: String? = null,
    val voiceMuted: Boolean = false,
    val voiceError: String? = null,
    val voiceIceServerCount: Int = 0,
    val voiceTurnAvailable: Boolean = false,
    val voiceInfrastructureError: String? = null,

    // Legacy name kept for compatibility: this flag now means VPN/network boost is active.
    val isBoosting: Boolean = false,
    val isTunnelConnecting: Boolean = false,
    val tunnelError: String? = null,
    val tunnelRxBytes: Long = 0L,
    val tunnelTxBytes: Long = 0L,
    val gameTrafficVerified: Boolean = false,
    val routeHealth: String = "IDLE",
    val routeProbeFailures: Int = 0,

    val clientPublicKey: String? = null,
    val identityError: String? = null,

    val wireGuardServerPublicKey: String = "",
    val wireGuardPort: Int = 51820,
    val tunnelAddress: String = "10.77.0.2/32",
    val dnsServer: String = "1.1.1.1",

    val controlPlaneUrl: String = "",
    val isAutoSelecting: Boolean = false,
    val isLanDiscovering: Boolean = false,
    val lanGatewayCount: Int = 0,
    val discoveredNodes: Int = 0,
    val selectedGatewayId: String? = null,
    val selectedGatewayRegion: String? = null,

    val gatewayHost: String = "",
    val gatewayPort: Int = 51821,
    val isProbing: Boolean = false,
    val probeError: String? = null,
    val serverLabel: String = "Сервер ещё не задан",

    val pingMs: Int? = null,
    val jitterMs: Int? = null,
    val packetLossPct: Double? = null,

    val boostStartedAtEpochMs: Long? = null,
    val boostSessionCount: Int = 0,
    val totalBoostSeconds: Long = 0,
    val lastBoostSeconds: Long = 0,
    val lastBoostPingMs: Int? = null,
    val lastBoostJitterMs: Int? = null,
    val lastBoostPacketLossPct: Double? = null,
)
